In [19]:
import matplotlib
import numpy as np

matplotlib.use('TKAgg')
import numpy as np
import nibabel as nib
from tqdm import tqdm
import os

In [20]:
example_filename = 'data/AMOS22/labelsTr/amos_0021.nii.gz'
img = nib.load(example_filename)
inputdir = 'data/AMOS22/labelsTr/'

In [38]:
# for file in tqdm(os.listdir(inputdir)):
file_path = os.path.join(inputdir, file)
img = nib.load(file_path)
x_pix = img.header['pixdim'][1]
y_pix = img.header['pixdim'][2]
z_pix = img.header['pixdim'][3]
volume_voxels = (x_pix * y_pix * z_pix)/1000
mask_np = np.array(img.dataobj)
print(mask_np.shape)
print(np.max(mask_np))
print(np.min(mask_np))
print(volume_voxels*np.sum(mask_np == i for i in range(15)))
#     for i in range(np.max(mask_np)):
#         final_volume = volume_voxels * mask_np
# print(final_volume)

(512, 512, 86)
15
0


C:\Users\sathy\AppData\Local\Temp\ipykernel_26628\2335310746.py:12: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.
  print(volume_voxels*np.sum(mask_np == i for i in range(15)))


[[[0.00305762 0.00305762 0.00305762 ... 0.00305762 0.00305762 0.00305762]
  [0.00305762 0.00305762 0.00305762 ... 0.00305762 0.00305762 0.00305762]
  [0.00305762 0.00305762 0.00305762 ... 0.00305762 0.00305762 0.00305762]
  ...
  [0.00305762 0.00305762 0.00305762 ... 0.00305762 0.00305762 0.00305762]
  [0.00305762 0.00305762 0.00305762 ... 0.00305762 0.00305762 0.00305762]
  [0.00305762 0.00305762 0.00305762 ... 0.00305762 0.00305762 0.00305762]]

 [[0.00305762 0.00305762 0.00305762 ... 0.00305762 0.00305762 0.00305762]
  [0.00305762 0.00305762 0.00305762 ... 0.00305762 0.00305762 0.00305762]
  [0.00305762 0.00305762 0.00305762 ... 0.00305762 0.00305762 0.00305762]
  ...
  [0.00305762 0.00305762 0.00305762 ... 0.00305762 0.00305762 0.00305762]
  [0.00305762 0.00305762 0.00305762 ... 0.00305762 0.00305762 0.00305762]
  [0.00305762 0.00305762 0.00305762 ... 0.00305762 0.00305762 0.00305762]]

 [[0.00305762 0.00305762 0.00305762 ... 0.00305762 0.00305762 0.00305762]
  [0.00305762 0.003057

In [41]:
organs_class = []
for file in tqdm(os.listdir(inputdir)):
    file_path = os.path.join(inputdir, file)
    img = nib.load(file_path)
    x_pix = img.header['pixdim'][1]
    y_pix = img.header['pixdim'][2]
    z_pix = img.header['pixdim'][3]
    volume_voxels = (x_pix * y_pix * z_pix)/1000
    mask_np = np.array(img.dataobj)
    for i in range(np.max(mask_np)):
        final_volume = volume_voxels * np.sum(mask_np == i)
        # print(final_volume)
        if final_volume > 0:
            organs_class.append(i)

100%|██████████| 240/240 [04:27<00:00,  1.12s/it]


In [42]:
organs_class

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10

In [43]:
from collections import Counter
Counter(organs_class)

Counter({0: 240,
         1: 237,
         2: 240,
         3: 239,
         4: 225,
         5: 239,
         6: 240,
         7: 238,
         8: 240,
         9: 240,
         10: 240,
         11: 239,
         12: 240,
         13: 197,
         14: 194})

In [44]:
from matplotlib import pyplot as plt

plt.hist(organs_class)
plt.show()